# Generated by Django 6.0.1 on 2026-02-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('due_date', 'name')},
        ),
        migrations.AddField(
            model_name='task',
            name='taskgroup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='blogpage.taskgroup'),
            preserve_default=False,
        ),
    ]
